### PR TITLE
update data.js

### PR DESCRIPTION
**Pull request by Ishukumarpathak**
New tree is added .

### CODE REVIEW

**Comment by Franqsanz** [comment]
Hello, I need you to change the ID, 31 already exists.

**Comment by Ishukumarpathak** [comment]
> Hello, I need you to change the ID, 31 already exists.

Ohk you can .

**Comment by Franqsanz** [comment]
I have merge conflicts, I'm going to close this PR, could you reopen one with the ID already changed?, thanks.

**Comment by Ishukumarpathak** [comment]
Ohk i will

**Pull request closed without merging**
